language: node_js
node_js:
  - "0.10"
services:
  - mongodb
  - redis-server
after_script:
  - npm run coveralls
env:
  global:
    secure: "qRzjZP4M+cymZJfO+0AZmviw4e5wuzwLQ3/eHV2rV77HvivwZCB9D/FdU1QnBlTIT87pQotPGXXkciVsc+zxyRd1xIVMzYaNn+TvKM3RTy5P+pAai8uL0mK7SO66ufJFVfLpdgqcfCP/JiM9rUBzhAI05KOQyk/YkAGT/LzKvhU"
