language: node_js
node_js:
  - "0.10"
services:
  - mongodb
  - redis-server
after_script:
  - npm run coveralls
env:
  global:
    secure: "vDVNauJP84zBUOBSB8/LkZ+CIlcqRwo4jm+9ed9Dt7w/Era/e6P9PWEwJkM4P3zUitZbn8OjqBDSbOYxPuqbH34//6l0Z7DYK7xN2acrdzXVLT8yidl5Dn/rs8BY6G9ZZ7mSg39v1KdIJSVPBHH3yyqlfwm2CqKovooNv1z3j6w="
